### PR TITLE
fixed deprecation warnings and added new "force user" option

### PR DESCRIPTION
**Pull request by morbidick**

### CODE REVIEW

**Comment by iangreenleaf** [comment]
Thanks! But, you should probably open a PR against [bertvv/ansible-role-samba](https://github.com/bertvv/ansible-role-samba), since that's the canonical repo. Mine is just a fork of that.

**Comment by morbidick** [comment]
yeah i know, but i need the role for ubuntu and dont wanna cherry pick :P

**Comment by iangreenleaf** [comment]
Ubuntu support is now in the origin repo, so you could go PR your patches there now!

**Comment by morbidick** [comment]
thx, i will look into it :)

**Pull request closed without merging**
